### ISSUE TITLE
Link base

### ISSUE THREAD

**Issue by jacek-mcp** [jacek-mcp/LoFi-music-generator#1]
Please, paste here all related links with a short description or hashtags

**Comment by jacek-mcp** [comment]
https://ai.plainenglish.io/building-a-lo-fi-hip-hop-generator-e24a005d0144
https://nsynthsuper.withgoogle.com/
https://ninaornina.medium.com/building-ai-to-make-lofi-hip-hop-an-introduction-to-recurrent-neural-networks-fe245be3a87d
https://mt.cs.upc.edu/seminars/
https://mt.cs.upc.edu/wp-content/uploads/CIFKA-NMT-meets-music.pdf
https://hal.archives-ouvertes.fr/hal-02923548v2/document
https://groove2groove.telecom-paris.fr/
https://www.kaggle.com/imsparsh/lakh-midi-clean
https://www.youtube.com/watch?v=nytHX412u5I


That's a copy of the links shared via email after the first meetup.

**Comment by jaumerib** [comment]
http://www.jordipons.me/apps/teaching-materials/

Link about Audio & Speech with Deep Learning
