### ISSUE TITLE
Lofi music generation studies

### ISSUE THREAD

**Issue by jacek-mcp** [jacek-mcp/LoFi-music-generator#2]
Hey, please post here links to papers/articles/repos strictly related to lofi music generation.

**Comment by jacek-mcp** [comment]
https://ai.plainenglish.io/building-a-lo-fi-hip-hop-generator-e24a005d0144
https://nsynthsuper.withgoogle.com/
https://ninaornina.medium.com/building-ai-to-make-lofi-hip-hop-an-introduction-to-recurrent-neural-networks-fe245be3a87d

**Comment by bpizzani** [comment]
Music generation code
Easy:
https://github.com/zacharykatsnelson/Lofi-Hip-Hop-Generator/blob/main/lstm.py

medium-hard:
https://github.com/SudharshanShanmugasundaram/Music-Generation
https://claytantor.wordpress.com/2021/05/13/using-machine-learning-to-generate-music/
https://github.com/alepintaudi/music-generation/blob/master/final-version/seq2seq.py
