### ISSUE TITLE
Architecture research

### ISSUE THREAD

**Issue by jacek-mcp** [jacek-mcp/LoFi-music-generator#3]
Let's discuss here how to put all the pieces together before starting the actual implementation.

**Comment by bpizzani** [comment]
We probably should document the following steps:

1 Data Retrieval.

2 Data (Audio) Format and Processing. (What format our audio needs to be processed through the Neural Network?)

3 Model Architecture. (LSTM ?)

4 Model Tunning (different Layers and Hyperparameters that would improve the results)

5 Output Evaluation.

6 Enhancements ( HTML webside to stream music etc.)

Let me know what you think.
